import AppKit
import Carbon.HIToolbox
import CoreGraphics

/// Puts text into the focused field of any app through the clipboard and ⌘V,
/// then gives the user their clipboard back.
@MainActor
public enum Paster {
    /// Marks our clipboard entry so clipboard managers and Spotlight history skip it
    /// (nspasteboard.org conventions).
    static let transientTypes: [NSPasteboard.PasteboardType] = [
        .init("org.nspasteboard.TransientType"),
        .init("org.nspasteboard.ConcealedType"),
        .init("org.nspasteboard.AutoGeneratedType"),
    ]
    static let sessionType = NSPasteboard.PasteboardType("dev.kovalskyi.voicemode.session")

    /// Bundle identifiers of terminals. They read the clipboard later than regular apps.
    public static let terminals: Set<String> = [
        "com.apple.Terminal", "com.googlecode.iterm2", "com.mitchellh.ghostty",
        "dev.warp.Warp-Stable", "net.kovidgoyal.kitty", "org.alacritty", "com.github.wez.wezterm",
    ]

    public enum Outcome: Equatable, Sendable {
        case pasted
        /// The focused field is a password field; nothing was inserted.
        case secureField
    }

    public static func paste(_ text: String, pressReturn: Bool = false) async -> Outcome {
        if FocusInspector.isSecureFieldFocused() || IsSecureEventInputEnabled() {
            return .secureField
        }
        let pasteboard = NSPasteboard.general
        let snapshot = PasteboardSnapshot(pasteboard)
        let session = UUID().uuidString

        pasteboard.clearContents()
        let item = NSPasteboardItem()
        item.setString(text, forType: .string)
        for type in transientTypes {
            item.setString("", forType: type)
        }
        item.setString(session, forType: sessionType)
        pasteboard.writeObjects([item])
        let ourChange = pasteboard.changeCount

        try? await Task.sleep(for: .milliseconds(60))
        KeyPoster.press(KeyPoster.keycode(for: "v"), flags: .maskCommand)
        if pressReturn {
            try? await Task.sleep(for: .milliseconds(120))
            KeyPoster.press(CGKeyCode(kVK_Return), flags: [])
        }

        let isTerminal = FocusInspector.frontmostBundleID().map(terminals.contains) ?? false
        try? await Task.sleep(for: .milliseconds(isTerminal ? 900 : 350))
        // Restore only if nobody copied something else in the meantime.
        if pasteboard.changeCount == ourChange, pasteboard.string(forType: sessionType) == session {
            snapshot.restore(to: pasteboard)
        }
        return .pasted
    }

    public static func copy(_ text: String) {
        let pasteboard = NSPasteboard.general
        pasteboard.clearContents()
        pasteboard.setString(text, forType: .string)
    }
}

/// Every item and type on the clipboard, copied as raw data.
struct PasteboardSnapshot {
    private let items: [[NSPasteboard.PasteboardType: Data]]

    init(_ pasteboard: NSPasteboard) {
        items = (pasteboard.pasteboardItems ?? []).map { item in
            var entry: [NSPasteboard.PasteboardType: Data] = [:]
            for type in item.types {
                if let data = item.data(forType: type) {
                    entry[type] = data
                }
            }
            return entry
        }
    }

    var isEmpty: Bool { items.isEmpty }

    func restore(to pasteboard: NSPasteboard) {
        pasteboard.clearContents()
        guard !items.isEmpty else { return }
        let restored = items.map { entry -> NSPasteboardItem in
            let item = NSPasteboardItem()
            for (type, data) in entry {
                item.setData(data, forType: type)
            }
            return item
        }
        pasteboard.writeObjects(restored)
    }
}

enum KeyPoster {
    static func press(_ keycode: CGKeyCode, flags: CGEventFlags) {
        let source = CGEventSource(stateID: .privateState)
        let down = CGEvent(keyboardEventSource: source, virtualKey: keycode, keyDown: true)
        let up = CGEvent(keyboardEventSource: source, virtualKey: keycode, keyDown: false)
        down?.flags = flags
        up?.flags = flags
        down?.post(tap: .cghidEventTap)
        up?.post(tap: .cghidEventTap)
    }

    /// Finds the key that types `character` in the current ASCII-capable layout,
    /// so ⌘V works on Dvorak and other layouts. Falls back to the ANSI position.
    static func keycode(for character: Character) -> CGKeyCode {
        let fallback = CGKeyCode(kVK_ANSI_V)
        guard
            let source = TISCopyCurrentASCIICapableKeyboardLayoutInputSource()?.takeRetainedValue(),
            let pointer = TISGetInputSourceProperty(source, kTISPropertyUnicodeKeyLayoutData)
        else {
            return fallback
        }
        let data = Unmanaged<CFData>.fromOpaque(pointer).takeUnretainedValue() as Data
        let target = String(character).utf16.first
        return data.withUnsafeBytes { raw -> CGKeyCode in
            guard let layout = raw.baseAddress?.assumingMemoryBound(to: UCKeyboardLayout.self) else { return fallback }
            for code in 0..<128 {
                var deadKeys: UInt32 = 0
                var length = 0
                var chars = [UniChar](repeating: 0, count: 4)
                let status = UCKeyTranslate(
                    layout, UInt16(code), UInt16(kUCKeyActionDisplay), 0, UInt32(LMGetKbdType()),
                    OptionBits(kUCKeyTranslateNoDeadKeysBit), &deadKeys, chars.count, &length, &chars
                )
                if status == noErr, length == 1, chars[0] == target {
                    return CGKeyCode(code)
                }
            }
            return fallback
        }
    }
}
